[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#0c0c16"
foreground = "#d8dee9"

[colors.normal]
black   = "#2c2c3d"
red     = "#ff6e6e"
green   = "#9ec875"
yellow  = "#ffa759"
blue    = "#70a7d4"
magenta = "#d291e0"
cyan    = "#96e0e0"
white   = "#d8dee9"

[colors.bright]
black   = "#414166"
red     = "#ff8d8d"
green   = "#b3d987"
yellow  = "#ffc57f"
blue    = "#9bb3d3"
magenta = "#ffa1ff"
cyan    = "#9cd8d8"
white   = "#ffffff"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 22

[font.bold]
family = "ZedMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "ZedMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "ZedMono Nerd Font"
style = "Italic"

[font.normal]
family = "ZedMono Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[window]
startup_mode = "Maximized"
decorations = "buttonless"
dynamic_title = false
opacity = 0.7
blur = true

[window.padding]
x = 4
y = 4
